"""
Username/slug resolution endpoint for Next.js middleware
Supports server-side 301 redirects from UID-based URLs to canonical slug URLs
"""

from flask import Blueprint, jsonify
import logging
from supabase_client import get_supabase_client

resolve_bp = Blueprint('username_resolve', __name__, url_prefix='/api/username')
logger = logging.getLogger('username.resolve')


@resolve_bp.route('/resolve/<user_id>', methods=['GET'])
def resolve_user_id_to_username(user_id: str):
    """
    Resolve Firebase UID to the canonical store slug for 301 redirects.

    Priority:
    1. businesses.url_slug  (canonical store URL — auto-generated by DB trigger)
    2. users.username        (fallback if no business record exists)

    Used by Next.js middleware to redirect:
      /store/{firebase_uid}  →  /store/{url_slug}
      /showcase/{firebase_uid}  →  /showcase/{url_slug}

    Response:
        {
            "success": true,
            "username": "my-store-slug"   // used as redirect target by middleware
        }

    Or if not found:
        {
            "success": false,
            "error": "Username not found"
        }
    """
    try:
        db = get_supabase_client()

        # Priority 1: businesses.url_slug (canonical store identifier)
        biz_result = db.table('businesses').select('url_slug').eq(
            'user_id', user_id
        ).limit(1).execute()

        if biz_result.data and biz_result.data[0].get('url_slug'):
            slug = biz_result.data[0]['url_slug']
            logger.info(f"✅ Resolved UID → business slug: {user_id[:8]}... → {slug}")
            return jsonify({
                "success": True,
                "username": slug
            }), 200

        # Priority 2: users.username (fallback)
        user_result = db.table('users').select('username').eq(
            'firebase_uid', user_id
        ).eq('username_status', 'active').limit(1).execute()

        if user_result.data and user_result.data[0].get('username'):
            username = user_result.data[0]['username']
            logger.info(f"✅ Resolved UID → username fallback: {user_id[:8]}... → {username}")
            return jsonify({
                "success": True,
                "username": username
            }), 200

        logger.warning(f"❌ No slug or username found for UID: {user_id[:8]}...")
        return jsonify({
            "success": False,
            "error": "Username not found"
        }), 404

    except Exception as e:
        logger.error(f"Error resolving user_id to username: {e}", exc_info=True)
        return jsonify({
            "success": False,
            "error": "Internal server error"
        }), 500
