-- ============================================================
-- Migration 017: Auto-Generate Order ID with Database Trigger
-- ============================================================
-- Purpose: Ensure ALL orders get a consistent order_id regardless of
-- which API creates them (Python backend, Next.js frontend, or direct SQL)
--
-- Format: First 8 characters of UUID, UPPERCASE
-- Example: "28C2CF22"
--
-- This creates a single source of truth for order_id generation
-- ============================================================

-- Step 1: Create the trigger function
CREATE OR REPLACE FUNCTION generate_order_id()
RETURNS TRIGGER AS $$
BEGIN
  -- Generate order_id from UUID if not already set
  -- Format: First 8 characters, uppercase (e.g., "28C2CF22")
  IF NEW.order_id IS NULL OR NEW.order_id = '' THEN
    NEW.order_id := UPPER(SUBSTRING(NEW.id::text FROM 1 FOR 8));
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Step 2: Drop existing trigger if it exists (for idempotent migrations)
DROP TRIGGER IF EXISTS trigger_generate_order_id ON orders;

-- Step 3: Create the trigger on INSERT
CREATE TRIGGER trigger_generate_order_id
BEFORE INSERT ON orders
FOR EACH ROW
EXECUTE FUNCTION generate_order_id();

-- Step 4: Backfill any existing orders that have NULL order_id
UPDATE orders 
SET order_id = UPPER(SUBSTRING(id::text FROM 1 FOR 8))
WHERE order_id IS NULL OR order_id = '';

-- Step 5: Add index for fast lookups by order_id (if not exists)
CREATE INDEX IF NOT EXISTS idx_orders_order_id ON orders(order_id);

-- Step 6: Add comment for documentation
COMMENT ON COLUMN orders.order_id IS 'Human-readable short order ID. Format: First 8 chars of UUID, uppercase (e.g., "28C2CF22"). Auto-generated by trigger.';

-- ============================================================
-- VERIFICATION QUERIES (Run after migration)
-- ============================================================
-- Check trigger exists:
-- SELECT tgname FROM pg_trigger WHERE tgname = 'trigger_generate_order_id';

-- Check function exists:
-- SELECT proname FROM pg_proc WHERE proname = 'generate_order_id';

-- Verify all orders have order_id:
-- SELECT COUNT(*) AS total, COUNT(order_id) AS with_order_id FROM orders;

-- Sample orders:
-- SELECT id, order_id, customer_name, created_at FROM orders ORDER BY created_at DESC LIMIT 10;
